baseURL = "https://dreamy-noyce-bcc7b2.netlify.com/"
languageCode = "en-us"
title = "Nlpirate"
theme = "beautifulhugo"

# syntax highlight
#pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true



[Params]
    useHLJS = true
    logo = "img/avatar-icon.png"
